options(repr.matrix.max.rows = 14, repr.matrix.max.cols = 100)
options(repr.font.family='DejaVu Sans')
options(repr.plot.pointsize = 24)
options(repr.plot.res = 240)
options(repr.plot.height = 4)
options(repr.plot.width = 5)
options(repr.plot.bg        = 'white')
options(repr.plot.antialias = 'gray')
