name: datawhys
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - ipympl
  - jupyterlab=1.2
  - matplotlib
  - nodejs=16
  - numpy
  - openssl<3
  - pandas
  - pip
  - plotly
  - ptvsd
  - python=3.7
  - scikit-learn
  - xeus=0.23
  - xeus-python
  - r-irkernel
  - r-modeest
  - r-corrplot
  - r-parsnip
  - r-rlang=1.0.3
  - r-vctrs=0.4.1
  - r-glue=1.6.2
  - r-tidyverse
  - r-tibble=3.1.7
  - r-tidymodels
  - r-caret
  - r-kknn
  - r-corrr
  - r-janitor
  - r-ggally
  - r-factoextra
  - r-ggfortify
  - r-psych
  - r-glmnet
  - r-rpart.plot
  - r-partykit
  - r-baguette
  - r-ranger
  - r-vip
  - r-remotes
  - r-xgboost
  - r-kernlab
  - r-klar
  - r-naivebayes
  - r-stacks
  - r-furrr
  - r-mlbench
  - r-scales